OPENAI_API_KEY= "sk-proj-pICTe9uTIjKhXj9eHBpvT3BlbkFJqwoOjCGmuj3Fpf2nYXFj"

AWS_ACCESS_KEY_ID = 'AKIAXECIORBBITAJXI5J'
AWS_SECRET_ACCESS_KEY = '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'
AWS_BUCKET_NAME = 'askphysics'

assistant_id = “asst_zv9GkFuTb5T4abAcUy4hBY1b”
